import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>OZZAO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          ຂໍອະໄພ ຈະກັບມາໃຊ້ງານໃນ ໄວໆນີ້.
        </h1>

        <p className={styles.description}>
          ໃນລະຫ່ວາງພວກເຮົາກຳລັງພັດທະນາທ່ານສາມາດຕິດຕໍ່ຊື້ ຜ່ານ Page OHZAO ໄດ້ຕະຫຼອດເວລາ
        </p>

        <div className={styles.grid}>
          <a href="https://www.facebook.com/ohzaocm" className={styles.card}>
            <h2>Facebook Page &rarr;</h2>
            <p>ກວດເບິ່ງສິນຄ້າເຂົ້າໃໝ່ ແລະ ຊື້ໄດ້ຕະຫລອດເວລາ</p>
          </a>
        </div>
      </main>
    </div>
  )
}
